### ISSUE TITLE
pgBackrest Stanza Create fails when using '--pgbackrest-storage-type s3'

### ISSUE THREAD

**Issue by nitai-nahaliel** [CrunchyData/postgres-operator#1155]
**Which example are you working with?**
pgo create cluster... --pgbackrest-storage-type s3
**What is the current behavior?**
'stanza-create' pod fails with -
"[ERROR: [50]: unable to acquire lock on file '/tmp/pgbackrest/db-archive.lock': Resource temporarily unavailable             HINT: is another pgBackRest process running?"
**What is the expected behavior?**
'stanza-create' succeeds and the cluster can backup to configured s3 bucket.
**Other information** (e.g. detailed explanation, related issues,  etc)
- Clusters created without '--pgbackrest-storage-type s3' work as expected ('stanza-create' completes successfully, and backup and restore tasks work with no issue
- Our environment is in it's own network (disconnected from the internet)

**Please tell us about your environment:**

* Operating System:
RHEL 7 (on the node running pgo client)
* Where is this running ( Local , Cloud Provider)
local
* Storage being used (NFS, Hostpath, Gluster, etc):
vsphere-standard
* Container Image Tag:
centos7-4.1.0
* PostgreSQL Version:
centos7-11.5-2.4.2
* Platform (Docker, Kubernetes, OpenShift):
Openshift 
* Platform Version:
3.11

**Comment by jkatz** [comment]
My first suggestion is to upgrade to v4.1.1 as it contains a number of bugfixes: https://github.com/CrunchyData/postgres-operator/releases/tag/v4.1.1

Unfortunately this does not provide enough information to troubleshoot the error. Are you running the Operator in a single namespace or are you running it using managing multiple namespaces? Did you try to create the same cluster twice? Do you have any logs about what happened before the failure occur?

**Comment by nitai-nahaliel** [comment]
Thank you for responding so quickly

We are planning upgrade to v4.1.1, but unfortunately because of organizational reasons, it might take us a while.

The operator is currently running in a single namespace (for testing).
I tried creating clusters with names i have never used, and the only thing that seemed to determine if the stanza creation will succeed is whether the s3 storage type is used or not.

These are the logs from the 'stanza-create' pod - 
```
time="2019-12-17T14:26:40Z" level=info msg="pgo-backrest starts"
time="2019-12-17T14:26:40Z" level=info msg="debug flag set to false"
time="2019-12-17T14:27:10Z" level=info msg="backrest stanza-create command requested"
time="2019-12-17T14:27:10Z" level=info msg="sleeping 30 seconds to avoid race with PG during startup"
time="2019-12-17T14:27:10Z" level=info msg="s3 flag enbled for backrest command"
time="2019-12-17T14:27:10Z" level=info msg="command to execute is [pgbackrest stanza-create  --repo-type=s3]"
time="2019-12-17T14:27:35Z" level=info msg="command is pgbackrest stanza-create  --repo-type=s3 "
time="2019-12-17T14:27:35Z" level=info msg="command terminated with exit code 50"
time="2019-12-17T14:27:35Z" level=info msg="output=[]"
time="2019-12-17T14:27:35Z" level=info msg="stderr=[ERROR: [50]: unable to acquire lock on file '/tmp/pgbackrest/db-archive.lock': Resource temporarily unavailable\n		HINT: is another pgBackRest process running?\n]
time="2019-12-17T14:27:35Z" level=info msg="command terminated with exit code 50"
```

**Comment by jkatz** [comment]
@nitai-nahaliel Not to give you another "upgrade" answer...but I'd recommend upgrading to [v4.2.0](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.2.0) which did a lot of work on the pgBackRest integration as backup/restore/recovery/healing is all built around pgBackRest.

We actually would come across this in testing (and subsequently fix). I recall a couple of scenarios where this occurred:

1. Race conditions in the code (which were fixed)
1. Trying to run a pgBackRest command that requires a lock (e.g. stanza-create) twice on the same repository.

I would strongly suggest upgrading. If you're still getting the issue, we can further dive into it.

**Comment by dvaldivia** [comment]
@jkatz I'm on the latest `4.6.1` and stanza is still failing with s3 backups, any way to debug this? I get `403` in the logs but i can use the provided credentials on any S3 client and verify they work, I also went to the secret and verified they are the expected values, everything seems to be in place, but stanza simply doesn't finish

**Comment by ibotty** [comment]
This happens here as well.  Anything to I can do to help debug that issue?

**Comment by jkatz** [comment]
The last poster opened up #2313 which determined it was an issue in the environment.

If you believe you have found a bug, I would recommend opening up an issue following the suggested format. If you are looking for general support, I would recommend reading [Support](https://access.crunchydata.com/documentation/postgres-operator/latest/).

**Comment by ibotty** [comment]
I am not looking for general support.  It seems to be a race of some sort, because it only happens sometimes.  Recreating the `pgtask` "fixed` it for now.  I will open another ticket when it happens again.

**Comment by FreeBugs** [comment]
This appears to happen on clusters that do not use a `local` storage class. Similar to the setup of OP, I am experiencing this on a cluster that uses vSphere storage. Adding a local storage provider (even as the non-default provider) seems to reliably fix the `Resource temporarily unavailable` issue.
