### ISSUE TITLE
An error occurred while running the pgbackrest backup job

### ISSUE THREAD

**Issue by yongjun925** [CrunchyData/postgres-operator#3636]
## Overview

The error message you received when running the pgbackrest backup command is:
`time="2023-04-21T13:25:40Z" level=info msg="crunchy-pgbackrest starts"
time="2023-04-21T13:25:40Z" level=info msg="debug flag set to false"
time="2023-04-21T13:25:40Z" level=info msg="backrest backup command requested"
time="2023-04-21T13:25:40Z" level=info msg="command to execute is [pgbackrest backup --stanza=db --repo=1 --type=diff]"
time="2023-04-21T13:25:40Z" level=info msg="output=[]"
time="2023-04-21T13:25:40Z" level=info msg="stderr=[hash e269349fb6ffb6c56d4a2864177815dac1b71659  - does not match local hash 4232abd12d46a8ae19db311c5d972b974abb9d11  -]"
time="2023-04-21T13:25:40Z" level=fatal msg="command terminated with exit code 1"`

## Environment

Please provide the following details:

- Platform: GKE
- Platform Version: (e.g. `1.20.3`, `4.7.0`)
- PGO Image Tag: ubi8-5.3.0-0
- Postgres Version 14
- Storage: hostpath

### REPRO

Provide steps to get to the error condition:

1. Run pgbackrest backup --stanza=db --repo=1 --type=diff
2. 
### EXPECTED

1. Provide the behavior that you expected.

### ACTUAL

1. Describe what actually happens

## Logs

Please provided appropriate log output or any configuration files that may help troubleshoot the issue. **DO NOT** include sensitive information, such as passwords.

## Additional Information

Please provide any additional information that may be helpful.

**Comment by tony-landreth** [comment]
Hello @yongjun925! Sometimes the initial pgbackup will fail, and then the job will be tried again. Did you see another backup job run after this failure?

**Comment by psavva** [comment]
I'm also seeing this error.

Every job is re-trying after a fresh clone of the cluster, and the backup keeps failing for the same reason.

```
fhirdb4-00-547d-0                               4/4     Running            0              34m
fhirdb4-backup-gw2c--1-29g68                    0/1     Error              0              2m8s
fhirdb4-backup-gw2c--1-p597z                    0/1     Error              0              2m20s
fhirdb4-backup-gw2c--1-vj664                    0/1     Error              0              2m18s
fhirdb4-backup-gw2c--1-zvll9                    0/1     Error              0              88s
```

time="2023-05-08T15:44:20Z" level=info msg="crunchy-pgbackrest starts"
time="2023-05-08T15:44:20Z" level=info msg="debug flag set to false"
time="2023-05-08T15:44:20Z" level=info msg="backrest backup command requested"
time="2023-05-08T15:44:20Z" level=info msg="command to execute is [pgbackrest backup --stanza=db --repo=1]"
time="2023-05-08T15:44:21Z" level=info msg="output=[]"
time="2023-05-08T15:44:21Z" level=info msg="stderr=[hash 44fd07087b45e1e12e579ddcd840c00b9d571fc8  - does not match local hash e4828666215c52b31547b727c5db330597881adc  -]"
time="2023-05-08T15:44:21Z" level=fatal msg="command terminated with exit code 1"

**Comment by ValClarkson** [comment]
Hi @psavva 

Unfortunately, I am unable to reproduce the error you are encountering.  Do you happen to have any more logs you could provide?  More details about your cluster initial creation and cloning would also be helpful.  Did the restore job happen to complete before you attempted to take a backup?

**Comment by Brice187** [comment]
Same here after initial start:
```
time="2023-06-06T15:24:46Z" level=info msg="crunchy-pgbackrest starts"
time="2023-06-06T15:24:46Z" level=info msg="debug flag set to false"
time="2023-06-06T15:24:46Z" level=info msg="backrest backup command requested"
time="2023-06-06T15:24:46Z" level=info msg="command to execute is [pgbackrest backup --stanza=db --repo=1 --type=full]"
time="2023-06-06T15:24:46Z" level=info msg="output=[]"
time="2023-06-06T15:24:46Z" level=info msg="stderr=[hash cf88bfd8218ef91606b60ff0834715c6dba4479b  - does not match local hash 4a367a3ff0d848171aa573900cc9dff75a284779  -]"
time="2023-06-06T15:24:46Z" level=fatal msg="command terminated with exit code 1"
```

**Comment by Brice187** [comment]
I resolved the issue by using s3 with tls.

**Comment by thewilli** [comment]
I've figured out what the cause of the problem was for me, but still I don't understand why this was happening. The hash is computed over all configuration files on both, the backup pod and the database instance pod. The sort order of those pods is different, though: While the file with a hyphen comes first on one pod, the underscore one is taken first with the other. This leads to the wrong checksum on the pods:

![CleanShot 2023-06-15 at 16 18 28@2x](https://github.com/CrunchyData/postgres-operator/assets/1206639/40657e62-4e59-4f00-a591-0dba0ea47c82)

No clue why this happens and how to fix it

**Comment by s3than** [comment]
We are showing the same issue in our usage, in multiple environments. Appears to be the same issue as shown here https://github.com/CrunchyData/postgres-operator/issues/3636#issuecomment-1593163070

Is there any sort of update on why this would be occurring?

**Comment by sl1pm4t** [comment]
We have identified that this hash difference is caused by different Locale settings on the backup pod vs the database pod.
In our case, the database pod have these set:
```
LC_ALL=en_US.utf-8
LANG=en_US.utf-8
```
and the backup pod has:
```
LANG=C.utf8
```
If I set the database pod to match, the hashes come out equal.
i.e.
```
unset LC_ALL
export LANG=C.utf8
```

**Comment by andrewlecuyer** [comment]
@sl1pm4t this has been resolved in the Crunchy Postgres for Kubernetes`v5.4.1` & `v5.3.3` releases, which are now available.  

Therefore, please ensure your operator, as well as all associated component containers (e.g. for PG, pgBackRest, etc.) have been upgraded, and you should no longer run into the hash mismatch error when taking backups.

**Comment by sl1pm4t** [comment]
Thanks @andrewlecuyer - can confirm that has fixed the issue for us (based on a single test I've done). 
I've looked across the various Crunchydata repos and can't find one that shows the `v5.4.1` release notes. Where should I be looking for the Crunchy Postgres changelog? 
Thanks!

**Comment by andrewlecuyer** [comment]
Thanks @sl1pm4t, glad to hear the issue has bee resolved!

And the link you referenced is indeed the correct place to find the release notes for Crunchy Postgres for Kubernetes:

https://access.crunchydata.com/documentation/postgres-operator/latest/releases

With this issue now resolved, I am going to proceed with closing this issue.  However, if anyone continues to have issues backups, please feel free to submit a new issue.

**Comment by jsierles** [comment]
I'm still seeing this issue. Can someone point to the specific commit that fixed it? I can't find release tags for v5.4.1. v4.7.10 is the last release [shown here](https://github.com/CrunchyData/postgres-operator/releases
).
